# DATA AGGREGATION

In [ ]:
import pandas as pd
happiness2015 = pd.read_csv("/kaggle/input/part-3-data-sets/World_Happiness_2015.csv")

In [ ]:
first_5_rows = happiness2015.head(5)
first_5_rows

In [ ]:
# Visualizing the happiness score of each country
import matplotlib.pyplot as plt
happiness2015['Happiness Score'].plot(kind='bar',title ='Happiness Scores', ylim=(0,10))
plt.show()

In [ ]:
Unique_regions = happiness2015['Region'].unique()
Unique_regions

In [ ]:
#Plotting for one region
so_asia = happiness2015[happiness2015['Region'] == 'Southern Asia']
so_asia.plot(x = 'Country', y = 'Happiness Score', kind = 'barh', title = 'Southern Asis Happiness Scores', xlim =(0,10))

**The GroupBy Operation**
* Split the dataframe into groups
* Apply a function to each group
* Combine the results into one data structure

In [ ]:
mean_happiness = {}
regions = happiness2015['Region'].unique()

for r in regions:

#Splitting the dataframe into groups
    region_group = happiness2015[happiness2015['Region'] == r]

# Apply a function to each group
    region_mean = region_group['Happiness Score'].mean()

# Combine the results into 1 data structure
    mean_happiness[r] = region_mean

In [ ]:
# Numbers of unique values in each region
happiness2015['Region'].value_counts()

In [ ]:
grouped = happiness2015.groupby('Region')
grouped.get_group('North America') #Selecting data dfroma certain group

In [ ]:
# Getting more information about the group
grouped.groups

In [ ]:
# Confirming the size of each groups
grouped.size()

In [ ]:
# Computing multiple aggregations at once
import numpy as np
grouped = happiness2015.groupby('Region')
happy_grouped = grouped['Happiness Score']
happy_mean_max = happy_grouped.agg([np.mean, np.max])
happy_mean_max

In [ ]:
# Using a function to aggregate the data
def dif(group):
    return(group.max() - group.mean())

happy_grouped.agg(dif)

In [ ]:
#Using pivot table to perform aggregation

pv_happiness = happiness2015.pivot_table(values='Happiness Score', index='Region',aggfunc=np.mean)
pv_happiness

In [ ]:
# Pivot table with multiple columns
grouped_by_region = happiness2015.pivot_table(['Happiness Score', 'Family'], 'Region')
grouped_by_region

In [ ]:
# Aggregating multiple columns and apply multiple functions at once
mean_min_max_by_region = happiness2015.pivot_table('Happiness Score', 'Region', aggfunc=[np.mean,np.min, np.max], margins = True)
mean_min_max_by_region

# COMBINING DATA USING PANDAS

In [ ]:
import pandas as pd
happiness2016 = pd.read_csv("/kaggle/input/part-3-data-sets/World_Happiness_2016.csv")
happiness2017 = pd.read_csv("/kaggle/input/part-3-data-sets/World_Happiness_2017.csv")

In [ ]:
happiness2016

In [ ]:
happiness2017

In [ ]:
# Adding new columns
happiness2015['Year'] = 2015
happiness2016['Year'] = 2016
happiness2017['Year'] = 2017

In [ ]:
happiness2016.head()

In [ ]:
happiness2017.head()

In [ ]:
head_2015 = happiness2015[['Year', 'Country', 'Happiness Score','Standard Error' ]].head(4)
head_2015

In [ ]:
head_2016 = happiness2016[['Country', 'Happiness Score', 'Year']].head(3)
head_2016

In [ ]:
concat_dataframe = pd.concat([head_2015, head_2016], axis=1)
concat_dataframe

In [ ]:
#Using pd merge 
pd.merge(left = head_2015, right = head_2016, on = 'Year')

# You can specify whether you want 'left join' or 'right join' using how = 'left'

In [ ]:
#left join
pd.merge(left = head_2015, right = head_2016, how = 'left', on = 'Year')

# Recall tha a left join includes all the rows from the 'left' dataframe along
# with any rows from the 'right' dataframe with a common key

# Use left when you dont want to drop any data from the left dataframe

In [ ]:
#right join
pd.merge(left = head_2015, right = head_2016, left_index = False, right_index = False, suffixes = ('_2015','_2016'), how = 'right', on = 'Year')
#right joins works by including all the rows from the right

# TRANSFORMING DATA USING PANDAS

In [ ]:
happiness2015 = happiness2015.rename(columns={'Economy GDP per Capita': 'Economy'})
happiness2015 = happiness2015.rename(columns={'Health(Life Expectancy)': 'Health'})
happiness2015 = happiness2015.rename(columns={'Trust(Government Corruption)': 'Trust'})

In [ ]:
happiness2015

In [ ]:
happiness2015

Applying a function element wise using the 'series.map', 'series.apply' & df.applymap() method

In [ ]:
def label(element):
    if element > 1:
        return 'High'
    else:
        return 'Low'
happiness2015['Economy Impact'] = happiness2015['Economy (GDP per Capita)'].map(label)
happiness2015['Economy Impact'] 

# 'series.map()' is used to apply a function to 1 column of the dataframe

**Reshaping data with Melt Function**

In [ ]:
pd.melt(df, id_vars = [], value_vars = []) 
id_vars = [] : Name of the column that should remain the same i 
value_vars = []
#This is used to reshape data from a wide format to a long format. 
#It essientially unpivots the data, making it easier to analyze and work with.

In [ ]:
melt = pd.melt(happiness2015, id_vars = ['Country','Region','Happiness Rank', 'Happiness Score'], value_vars = ['Col 1', 'Col2', 'Col3', 'Col4'])

# WORKING WITH MISSING AND DUPLICATED DATA

In [ ]:
shape_2015 = happiness2015.shape
shape_2015

In [ ]:
shape_2016 = happiness2016.shape
shape_2016

In [ ]:
shape_2017 = happiness2017.shape
shape_2017

**In panda, missing value are generally regarded as NAN**

In [ ]:
missing = happiness2015['Happiness Score'].isnull()
missing_2015 = happiness2015[missing]
missing_2015

In [ ]:
happiness2015.isnull().sum()

In [ ]:
happiness2016.isnull().sum()

In [ ]:
happiness2017.isnull().sum()

WORKFLOW FOR CLEANING DEALING WITH MISSING DATA
* Check for errors in data cleaning/transformation
* Use data from additional sources to fill missing values
* Drop row/column
* Fill missing values with reasonable estimates computed from the available data

In [ ]:
happiness_2015 = pd.read_csv("/kaggle/input/part-3-data-sets/wh_2015.csv")
happiness_2016 = pd.read_csv("/kaggle/input/part-3-data-sets/wh_2016.csv")
happiness_2017 = pd.read_csv("/kaggle/input/part-3-data-sets/wh_2017.csv")
combined = pd.concat([happiness_2015, happiness_2016, happiness_2017], ignore_index=True)

In [ ]:
happiness_2015

In [ ]:
happiness_2016

In [ ]:
happiness_2017

In [ ]:
combined

In [ ]:
combined.isnull().sum()

As a reminder, below is a list of common string methods you can use to clean the columns:
* series.str.split() - split each element in the series
* series.str.strip() - strips whitespace from each string in the series
* series.str.lower() - converts strings in the series to lower case
* series.str.upper() - converts strings in the series to uppercase
* series.str.get() - retrieves the ith element of each element in the series
* series.str.replace() - replace a regex or string in the series with another string
* series.str.cat() - concatenates strings in a series
* series.str.extract() - extracts substrings from the series matching a regex pattern

In [ ]:
# formatting the columns
happiness_2015.columns.str.replace('.',' ').str.replace('\s+',' ').str.strip().str.upper()

In [ ]:
happiness_2015.rename(columns={'ECONOMY (GDP PER CAPITA)': 'ECONOMY GDP PER CAPITA'}, inplace=True)

In [ ]:
happiness_2015

In [ ]:
happiness_2016.columns.str.replace('.',' ').str.replace('\s+',' ').str.strip().str.upper()

In [ ]:
happiness_2016.columns.str.replace('.',' ').str.replace('\s+',' ').str.strip().str.upper()

In [ ]:
happiness_2017.columns.str.replace('.',' ').str.replace('\s+',' ').str.strip().str.upper()

In [ ]:
happiness_2015

In [ ]:
combined.isnull().sum()

In [ ]:
# Leaning more about the missing value by visualizing with heat map

import seaborn as sns
combined_updated = combined.set_index('Year')
sns.heatmap(combined_updated.isnull(), cbar = False)
plt.show

Our observations from the heat map
* No values are missing in the COUNTRY column
* There are some rows in the 2015, 2016 and 2017 data with missing values in all columns except the COUNTRY column
* Some columns only have data populated for one year
* It looks like the REGION data is missing for the year 2017

**IDENTIFYING DUPLICATE VALUES**

In [ ]:
dups = combined.duplicated(['Country', 'Year'])
combined_dups = combined[dups]
combined_dups

In [ ]:
# Correcting Duplicated Values
combined['COUNTRY'] = combined['Country'].str.upper()
dups = combined.duplicated(['Country', 'Year'])
combined_dups = combined[dups]
combined_dups

In [ ]:
# Inspecting all the rows for SOMALILAND REGION in COMBINED

somaliland_combined = combined[combined['Country']] == 'Somaliland Region'

We can use 'df.drop_duplicated' to drop the duplicate rows

* We can use **'df.drop()'** to drop columns we don't need for our analysis.
* However as we work with bigger data sets, it can sometimes be tedious to create a long list of colums names to drop.
* Instead we can use **df.dropna()**. By default, this method will drop rows with any missing values. To drop columns, we can set axis parameter to equal to 1 i.e **df.drop(axis =1)**
* We can use **thresh** parameter to only drop columns if they contain below a certain number of non-null values.
* To confirm the number of values that are not missing **df.notnull()**

In [ ]:
combined.notnull().sum().sort_values()

**Analysing Missing Data**
* Is the missing data needed to accomplish our end goal?
* How will removing or replacing the missing values affects our analysis?
* What percentage of the data is missing?
* Will dropping missing values cause us to lose valuable information in other columns?
* Can we identify any patterns in the missing data?

There are many options for choosing the replacement of NAN
* A constant value
* The mean of the column
* The median of the column
* The mode of the column

We use **series.fillna()** for replacing NAN